PWD=$(shell pwd)

# path to aap-juce directory.
AAP_JUCE_DIR=$(PWD)/external/aap-juce

# path to application repo. The default is the submodule path.
APP_SRC_DIR=$(PWD)/external/vital

# base app name
# We avoid naming "Vital" (see vital/README)
APP_NAME=vitaloid

APP_BUILD_DIR=apps/vital/plugin
APP_COPY_DIR=apps/vital
LIBFILES=builds/linux_vst/build/Vial.a

# aap_metadata.xml source
AAP_METADATA_XML_SOURCE=$(PWD)/apps/vitaloid.aap_metadata.xml

# diff file to app, generated by git diff. "-" if there is no patch.
PATCH_FILE=$(PWD)/apps/vitaloid-aap.patch

# diff depth, depending on the nested directory in the source tree, if patch exists.
PATCH_DEPTH=1

JUCE_DIR=$(shell pwd)/external/JUCE

JUCE_PATCHES= \
        $(AAP_JUCE_DIR)/juce-patches/6.0.5/support-plugin-ui.patch \
        $(AAP_JUCE_DIR)/juce-patches/6.0.5/juce-component-peer-view-touch.patch
        #$(AAP_JUCE_DIR)/juce-patches/7.0.12/disable-cgwindowlistcreateimage.patch

# Enable this if it is instrument (and unless you don't want to support MIDI input).
ENABLE_MIDI_DEVICE_SERVICE=1 

# Enable if it should skip metadata generator. Plugins need it, hosts don't.
# SKIP_METADATA_GENERATOR=1

# For update-aap-metadata tasks
ifeq ($(shell uname), 'Darwin')
PLAT_BUILD_DIR=macosx
else
PLAT_BUILD_DIR=linux_vst
endif
BUILDS_DIR=builds
METADATA_GENERATOR_EXTRA_LDFLAGS=-lGL

EXTERNAL_PRE_PROJUCE_TASKS=replace-juce-modules

EXTERNAL_POST_PROJUCE_TASKS=replace-app-build-gradle

include $(AAP_JUCE_DIR)/Makefile.common

include Makefile.exttasks
